### ISSUE TITLE
We need to run on OpenShift as a provider

### ISSUE THREAD

**Issue by arilivigni** [openshift/contra-hdsl#23]
Support provision a container, configure, run tests as we do with other providers like Openstack, AWS, and Beaker

**Comment by ifireball** [comment]
is any progress being made on this?

**Comment by skatlapa** [comment]
Hello @ifireball you can take a look at the progress here - https://github.com/openshift/contra-hdsl/pull/53
I have some nits to refactor(WIP), should be done by mid-week. 
Let me know your suggestion/questions on the PR, thanks.

**Comment by ifireball** [comment]
@skatlapa I'm afraid I'm not familiar enough with the code to make any meaningful comments on the PR, but may I suggest you mention the issue in the commit message so that GitHub places update on the PR status here?

Anyway its good to know progress is being made.

**Comment by lioramilbaum** [comment]
I have reason to believe that this issue is relevant to the challenge I a facing with the Ember-CSI project. @arilivigni @ifireball correct if I am wrong. If not, do you have an estimation when I can start using/testing it?

**Comment by arilivigni** [comment]
@lioramilbaum Pleas provide more details of why this is required.  Can you create this use case outside the DSL?

**Comment by lioramilbaum** [comment]
@arilivigni Haven't we discussed it? Have a look at the Trello card. 
I can bypass the DSL if this is the right move.

**Comment by arilivigni** [comment]
@lioramilbaum so do you have this running in OpenShift already is my question.  The DSL can wrap around this but I want to make sure this is the right approach.  Do you have Ember-CSI running?  In any case this is in review in the PR.  You could clone the PR itself and give it a try and provide feedback to @skatlapa

**Comment by lioramilbaum** [comment]
@arilivigni net yet, I am doing the training as you advised. I will give it a try as soon as I complete.

**Comment by skatlapa** [comment]
@lioramilbaum Hi, sorry for later reply, you can actually clone the PR and start testing, it should work with minishift/contra-env-setup if that's what you are using.
I can confirm working by today or tomorrow. 
Btw.. if you haven't used HDSL before I'd suggest looking at sample_files[1] that we need to input to HDSL. That's currently OpenStack example, I will provide you an example for OCP/OKD once I confirm testing.
Thanks.

[1] - https://github.com/robnester-rh/hdsl_sample

**Comment by skatlapa** [comment]
@ifireball ack, re naming commit, will do, thanks!

**Comment by skatlapa** [comment]
@lioramilbaum Please hold off on testing the PR https://github.com/openshift/contra-hdsl/pull/53 until I confirm it works and provide you a sample contra.yaml, as there may be some bugs and I am not done testing yet.

**Comment by skatlapa** [comment]
Hi @ifireball  @lioramilbaum currently there are some bugs with Linchpin which is delaying the OKD provider PR for HDSL, they should be fixed in 1-2 days, you can track them here - 
https://github.com/CentOS-PaaS-SIG/linchpin/issues/774
https://github.com/CentOS-PaaS-SIG/linchpin/issues/771

**Comment by lioramilbaum** [comment]
@arilivigni @skatlapa @ifireball We need a docker image  (from RH registry) which includes the virtualization packages?  Is there such an image? I have done some searching with no avail yet.

**Comment by arilivigni** [comment]
@lioramilbaum we do but that is not part of this issue nor is it part of H-DSL that is just a container that can run.  You can call it with the H-DSL but it is not connected to the work done on H-DSL.  I will send you information separately

**Comment by lioramilbaum** [comment]
@arilivigni thx for the clarification. It is part of deploying Contra-HDSL in Ember-CSI CI.

**Comment by arilivigni** [comment]
@skatlapa Any update on the PR to support this so @lioramilbaum can use the H-DSL?

**Comment by skatlapa** [comment]
@arilivigni @lioramilbaum The okd provider in Linchpin is yet to be merged. Once merged I should be quickly able to make the new changes in H-DSL. Here is the linchpin PR - https://github.com/CentOS-PaaS-SIG/linchpin/pull/783
