### ISSUE TITLE
ansible executor image - virtualenv is missing

### ISSUE THREAD

**Issue by lioramilbaum** [openshift/contra-hdsl#61]
I have created an application with the command:
```
./oc new-app contrainfra/ansible-executor:latest
```
ssh to the pod:
```
./oc rsh ansible-executor-1-deploy
```

Listing virtualenv:
```
sh-4.2$ ls /usr/bin/virtualenv
ls: cannot access /usr/bin/virtualenv: No such file or directory
```

Running a local container (on my laptop) based on the docker hub image:
```
docker run -it  contrainfra/ansible-executor:latest /bin/bash
```

Listing virtualenv:
```
bash-4.4$ ls /usr/bin/virtualenv
/usr/bin/virtualenv
```

**Comment by arilivigni** [comment]
Maybe an access problem with the virtualenv, but this isn't a h-DSL issue.   Can you try running the container in a Jenkins pipeline?  We need more data

**Comment by lioramilbaum** [comment]
The image pushed to ember-csi Openshift project wasn't compatible with the one in docker hub. Maybe a tagging issue. Also, the image stream triggers image build when there is the latest tag is updated, but, contra-HDSL uses the stable one. 
Maybe, an automation is in place.
